trigger:
  branches:
    include:
      - develop

resources:
  repositories:
    - repository: 'GitHubRepo'
      type: 'github'
      name: 'darovero/daroveroapp'
      ref: 'refs/heads/develop'
      endpoint: 'github_darovero'

pool:
  vmImage: 'windows-latest'

jobs:
- job: 'Build'
  displayName: 'Build App DaroveroApp'

  steps:
  - checkout: 'GitHubRepo'

  - task: PowerShell@2
    displayName: 'Build Project'
    inputs:
      targetType: 'inline'
      script: |
          # Build the project
          dotnet build

          # Publicar el proyecto en la carpeta de publicación
          dotnet publish -c Release -o $(Build.SourcesDirectory)\build\deploy_package

          # # Verificar si los archivos se publicaron correctamente
          # if (-Not (Test-Path -Path "$(Build.SourcesDirectory)\build\deploy_package")) {
          #   Write-Error "Directory '$(Build.SourcesDirectory)\build\deploy_package' does not exist after publish."
          #   exit 1
          }

  # - task: PowerShell@2
  #   displayName: 'Verify Publish Folder'
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       if (-Not (Test-Path -Path "$(Build.SourcesDirectory)\build\deploy_package")) {
  #         Write-Error "Directory '$(Build.SourcesDirectory)\build\deploy_package' does not exist."
  #         exit 1
  #       }

  - task: ArchiveFiles@2
    displayName: 'Zip Build Folder'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)\build\deploy_package'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)\build-$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\build-$(Build.BuildId).zip'
      artifactName: 'drop'
      artifactType: 'Container'