trigger:
  branches:
    include:
      - develop

resources:
  repositories:
    - repository: 'GitHubRepo'
      type: 'github'
      name: 'darovero/daroveroapp'
      ref: 'refs/heads/develop'
      endpoint: 'github_darovero'

pool:
  vmImage: 'windows-latest'

jobs:
- job: 'Build'
  displayName: 'Build App'

  steps:
  - checkout: 'GitHubRepo'

- task: AzurePowerShell@5
  displayName: 'Build Project'
  inputs:
    azureSubscription: 'all_spn'
    ScriptType: 'InlineScript'
    Inline: |
      # Restaurar paquetes NuGet (si es necesario)
      dotnet restore

      # Construir el proyecto
      dotnet build

      # Publicar el proyecto en la carpeta de publicación
      dotnet publish -c Release -o $(Build.SourcesDirectory)\build\deploy_package
    azurePowerShellVersion: 'LatestVersion'  # Usar la última versión de Azure PowerShell
    workingDirectory: '$(System.DefaultWorkingDirectory)'  # Asegúrate de trabajar en el directorio correcto

  - task: ArchiveFiles@2
    displayName: 'Zip Build Folder'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)\build\deploy_package'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)\build-$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\build-$(Build.BuildId).zip'
      artifactName: 'drop'
      artifactType: 'Container'