trigger:
  branches:
    include:
      - develop

resources:
  repositories:
    - repository: 'GitHubRepo'
      type: 'github'
      name: 'darovero/daroveroapp'
      ref: 'refs/heads/develop'
      endpoint: 'github_darovero'

pool:
  vmImage: 'windows-latest'

jobs:
- job: 'Build'
  displayName: 'Build App'

  steps:
  - checkout: 'GitHubRepo'

  - task: AzurePowerShell@5
    displayName: 'Build Project'
    inputs:
      targetType: 'inline'
      script: |
          # Restore NuGet packages (if necessary)
          dotnet restore

          # Build the project
          dotnet build

          # Publicar el proyecto en la carpeta de publicación
          dotnet publish -c Release -o $(Build.SourcesDirectory)\build\deploy_package

  - task: ArchiveFiles@2
    displayName: 'Zip Build Folder'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)\build\deploy_package'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)\build-$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\build-$(Build.BuildId).zip'
      artifactName: 'drop'
      artifactType: 'Container'